name: Docker Images CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [debian-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: docker build and push host
      run: |
        docker login --username rsimba --password-stdin ghcr.io <<<${{ secrets.GHCR_TOKEN }}
        docker build ./host --tag ghcr.io/rsimba/host:latest
        docker push ghcr.io/rsimba/host:latest
