name: Docker Images CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker build and push host
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        context: ./host
        tags: ghcr.io/rsimba/host:latest
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
