name: Docker Images CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Push Host Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: rsimba/host
        registry: ghcr.io
        dockerfile: /docker/host/Dockerfile
        directory: docker/host
        tag: latest
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
