name: Docker Images CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker build and push host
      run: |
        docker login --username rsimba --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        docker build ./host --tag host:latest
        docker push ghcr.io/rsimba/host:latest

