name: Docker Images CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker build host
      run: docker build ./host --file Dockerfile --tag host:$(date +%s)
    - name: docker push
      run: docker push host
