name: Docker Images CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build and push host docker image
      run: |
        docker login --username rsimba --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        docker build ./host --tag ghcr.io/rsimba/host:latest
        docker push ghcr.io/rsimba/host:latest

    - name: build and push  automation image
      run: |
        docker login --username rsimba --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        docker build ./automation --tag ghcr.io/rsimba/automation:latest
        docker push ghcr.io/rsimba/automation:latest

    - name: build and push cisco-pyats image
      run: |
        docker login --username rsimba --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        docker build ./cisco-pyats --tag ghcr.io/rsimba/cisco-pyats:latest
        docker push ghcr.io/rsimba/cisco-pyats:latest

    - name: build and push juniper-pyez image
      run: |
        docker login --username rsimba --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        docker build ./juniper-pyez --tag ghcr.io/rsimba/juniper-pyez:latest
        docker push ghcr.io/rsimba/juniper-pyez:latest

    - name: build and push nac-server image
      run: |
        docker login --username rsimba --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        docker build ./nac-server --tag ghcr.io/rsimba/nac-server:latest
        docker push ghcr.io/rsimba/nac-server:latest

    - name: build and push syslog-server image
      run: |
        docker login --username rsimba --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        docker build ./syslog-server --tag ghcr.io/rsimba/syslog-server:latest
        docker push ghcr.io/rsimba/syslog-server:latest
