name: Docker Images CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker build host
      run: |
        docker login --username rsimba --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        docker build ./docker/host --file Dockerfile --tag host:$(date +%s)
        docker push ghcr.io/rsimba/docker/host:latest

